# Generated by Django 5.2.3 on 2025-06-25 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_userprofile_location_userprofile_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickuprequest',
            name='pickup_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
